# Generated by Django 4.2.3 on 2023-09-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trainingtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtemplate',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='trainingtemplate',
            name='sets',
        ),
        migrations.CreateModel(
            name='TrainingTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exercise')),
                ('training_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainingtemplate')),
            ],
        ),
    ]
