# Generated by Django 4.2.3 on 2023-10-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_trainingtemplate_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplateexercise',
            name='custom_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customeexercise'),
        ),
        migrations.AlterField(
            model_name='trainingtemplateexercise',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exercise'),
        ),
    ]
